### ISSUE TITLE
Module compiled with Swift 5.0, cannot be imported by the Swift 5.1

### ISSUE THREAD

**Issue by dimaosa** [Veriff/veriff-sample-ios#10]
Hi there, 

We currently have this error when trying to compile in Xcode 11

Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: `.../Pods/VeriffSDK/Veriff.framework/Modules/Veriff.swiftmodule/x86_64.swiftmodule`

Could you let me know if there are any plans to update Veriff SDK?

**Comment by nicolla1003** [comment]
Already discussed about this issue.
See https://github.com/Veriff/veriff-sample-ios/issues/9

**Comment by MertCelik** [comment]
Hello @dimaosa !

We are currently working on structuring bleeding edge builds but meanwhile we pushed some builds that is compatible with Xcode 11. Could you please use the version below for that?

pod 'VeriffSDK', '2.5.0-patch3'

Thank you very much for the assistance @nicolla1003 !

**Comment by dimaosa** [comment]
Thanks, @nicolla1003 !

Should we keep the issue Open, until the issue would be totally fixed? So other people would see it. @MertCelik

**Comment by MertCelik** [comment]
yes @dimaosa , let's keep it Open for now and I can clean it up when we are done with it :)

**Comment by aleksasimiczuper** [comment]
We have again problem with Xcode 11.2 while using library '2.50-patch3' :
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

**Comment by mwawrusch** [comment]
Same problem. Looks like Stackoverflow has a solution
https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler

This is what needs to be done at the veriff side:

OK, Turns out if you watch the WWDC video, they explain it: https://developer.apple.com/videos/play/wwdc2019/416/

You need to set the Build Libraries for Distribution option to Yes in your framework's build settings, otherwise the swift compiler doesn't generate the neccessary .swiftinterface files which are the key to future compilers being able to load your old library.

This ends up in your project.pbxproj file as:

BUILD_LIBRARY_FOR_DISTRIBUTION = YES;

**Comment by MertCelik** [comment]
Hi everyone , we really appreciate your patience on this. It has been an interesting release cycle by Apple and we worked hard to keep things rolling. 

We have just released version 2.6.1 that supports Swift 5.1.2 (built with Xcode 11.2.1) and have the build for distribution enabled. The full release notes will be deployed today to the link below but the SDK is already available through Cocoapods.

Also we moved our communications and documentations to [https://developers.veriff.com/](https://developers.veriff.com/). Next time if you kindly contact us through there, we will be much faster to react 💪
