### ISSUE TITLE
Which version of SDK is currently on CocoaPods?

### ISSUE THREAD

**Issue by dimaosa** [Veriff/veriff-sample-ios#7]
I am lost with your version naming because in Cocoapods latest one is 2.0.5 and in Readme, SDK version is 2.5.0

**Comment by dimaosa** [comment]
@kristjanpirnpuu @lauriesk

**Comment by MertCelik** [comment]
Hey, @dimaosa!
Thank you for contacting us and sorry for getting back to you little late!

You are right, latest version is 2.5.0 at the moment. There is an issue causing Cocoapods to fail to generate new page after publishing new pod. Unfortunately this issue is there for quite some time on Cocoapods. You can check [a related issue here.](https://github.com/CocoaPods/cocoapods.org/issues/265)

While we keep an eye on this for fixing, there is no updates so far from Cocoapods side. We are very sorry for the inconvenience this caused to you.

**Comment by dimaosa** [comment]
So, is it so that version 2.0.5 (in CocoaPods) point to 2.5.1(VeriffSDK version)?

**Comment by MertCelik** [comment]
No, Cocoapods version 2.0.5 will is pointing to 2.0.5 and 2.5.1 pointing to 2.5.1. The issue is only the documentation on the cocoapods.org page. The pod system still works as it's used to be. It's just the versions after 2.0.5 are not rendered on the Cocoapods.org but you can check they are actually on the [cocoapods repository](https://github.com/CocoaPods/Specs/tree/master/Specs/e/4/9/VeriffSDK).

So feel free to use 2.5.1 in your podfile and it will download version 2.5.1

**Comment by dimaosa** [comment]
Understood, thanks for help @MarkKerner
