### ISSUE TITLE
How much size would VeriffSDK take on iOS Device? 

### ISSUE THREAD

**Issue by dimaosa** [Veriff/veriff-sample-ios#8]
I noticed the VeriffSDK is using CocoaPod `VeriffWebRTC` which weight 810mb. So I am quite worried about it.

@MertCelik

**Comment by MertCelik** [comment]
Hey @dimaosa ,
You are right, even WebRTC source code itself is quite big(6GB). But this is because it holds all architecture types possible. In case of iOS/OSX libraries it is around the value you have mentioned. But this is stripped out when you build the app. It's hard to give exact size since it can vary depending on the devices. But whole library is varies between 15-20MBs. You can check the size of [our app in AppStore](https://apps.apple.com/us/app/veriff/id1467907532) too!

**Comment by nicolla1003** [comment]
I can confirm that it's not that big when you build the app.

**Comment by dimaosa** [comment]
Thanks!
